- name: Create Conig file - {{ item.job_name }}
  ansible.builtin.template:
    src: jjob.xml
    dest: /tmp/jjob.xml

- name: Create a jenkins job - {{ item.job_name }}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/jjob.xml') }}"
    name: -{{ item.job_name }}
    password: admin123
    url: http://172.31.29.222:8080
    user: admin